# Files
executable = scriptcondor.sh
output = outputcondorMuonJet/log/scriptcondor_$(Process).out
error = outputcondorMuonJet/log/scriptcondor_$(Process).err
log = outputcondorMuonJet/log/scriptcondor_$(Process).log
#arguments    = $(Process)


transfer_input_files = $(filename)
arguments            = $(filename)  outputcondorMuonJet/output_$(Process).root MuonJet



# File transfer behavior
#should_transfer_files = no
#when_to_transfer_output = ON_EXIT

# Resource requests
#request_cpus   = 4
request_memory = 100MB
request_disk   = 100MB

# Optional resource requests
#+xcount = 4            # Request 4 cores
#+maxMemory = 4000      # Request 4GB of RAM
#+maxWallTime = 120     # Request 2 hrs of wall clock time
#+remote_queue = "osg"  # Request the OSG queue

# Run job
#queue filename matching files /pnfs/iihe/cms/store/user/lathomas/Muon/Run2022C_PromptReco_v1_DataRun3_L1Study_SingleMuforJME/220822_150627/0000/output_*.root /pnfs/iihe/cms/store/user/lathomas/SingleMuon/Run2022C_PromptReco_v1_DataRun3_L1Study_SingleMuforJME/220817_075727/0000/output_*.root
#queue filename matching files /pnfs/iihe/cms/store/user/lathomas/EGamma/Run2022*_DataRun3_L1Study_SinglePhotonforJME/220908*/*/*.root
queue filename matching files /pnfs/iihe/cms/store/user/lathomas/*Muon*/Run2022*_DataRun3_L1Study_Single*forJME/220908*/*/*.root

#queue filename matching files /pnfs/iihe/cms/store/user/lathomas/SingleMuon/Run2022B_PromptReco_v1_DataRun3_L1Study_SingleMuforJME/220908_123342/0000/*.root
#queue 100 